### ISSUE TITLE
Match statements don't match lines with carriage returns

### ISSUE THREAD

**Issue by Matty9191** [whyscream/postfix-grok-patterns#114]
I've been using your ES postfix grok patterns for quite some time. Amazing work! After upgrading to ES 5.5 I noticed that postfix messages were no longer getting tagged. After a bit of debugging I noticed that the following match:

match          => [ "syslog_message", "^%{POSTFIX_SMTP}$" ]

Doesn't match syslog_messages ending with newlines or carriage returns. If I feed the following message to logstash:

"message" => "Aug 31 00:00:03 foo01 postfix/smtp[9147]: 30D232017FA: to=<f@bar.com>, relay=mail.foo.com[1.2.3.4]:25, delay=1.1, delays=0.04/0/0.03/1, dsn=2.6.0, status=sent (250 2.6.0 <20170831040002.13DE9B74@ick.bar.net> [InternalId=306728030] Queued mail for delivery)\r"

It spits out a _grok_postfix_smtp_nomatch. If I change the match to include carriage returns and newlines:

match          => [ "syslog_message", "^%{POSTFIX_SMTP}(\r|\n|$)" ]

It works as expected. I'm debating between altering the match or using gsub in my syslog input filter to remove carriage returns. Have you by any chance come across this? If so, which method did you use to get everything working? Thanks again for the amazing work!

**Comment by whyscream** [comment]
The newline should not be there, it's not part of the format generated by postfix, but somehow inserted by your pipeline. You should research the way your postfix logs get into logstash, and find out why the newline ends up in your data, and then fix that issue (or file a bug for it).

We can't add any support for random crap inserted into your data. When you send your logging through an IM service that automatically, converts each occurrence of `foo :(bar)` into `foo ☹bar)`, we can't cope with that either. Your input data should be correct :)
