### ISSUE TITLE
Postfix QueueID Size

### ISSUE THREAD

**Issue by Belphemur** [whyscream/postfix-grok-patterns#115]
Hello,

In your Grok pattern, you chose to have the postfix ID as 15+. Upon testing at my workplace, we discovered that our ids are 14 characters and not 15.

Can you change your rule for 14+ ?

**Comment by whyscream** [comment]
Based on http://www.postfix.org/postconf.5.html#enable_long_queue_ids, the queue is either short or long. 

* short: `The name format is: 5 characters for the time in microseconds; the remainder is the file inode number.`
* long: `The name format is: 6 or more characters for the time in seconds, 4 characters for the time in microseconds, the 'z'; the remainder is the file inode number encoded in the first 51 characters of the 52-character alphabet.`

In the grok pattern this is currently represented as lengths 6 for short (5 +1) and 15 (arbitrary) for long. I'll update the grok to support the minimum length of 6 (time) + 4 (microtime) + 1 (`z`) + 1 (inode).

**Comment by Belphemur** [comment]
That's perfect!

I agree that 12 is the minimum length for those ids.

Thank you.

⁣Sent from Blue ​

**Comment by whyscream** [comment]
Fixed by #117
