### ISSUE TITLE
_grok_postfix_command_counter_data_nomatch

### ISSUE THREAD

**Issue by lukbaum** [whyscream/postfix-grok-patterns#120]
I get the above error for the following line:

`helo=1 auth=0/1 quit=1 commands=2/3`

in the field

`postfix_command_counter_data`

It's because the auth-field is missing in postfix.grok. Wouldn't it be better to simply use the kv filter for parsing this field? Should be a more general (and more robust) solution.

**Comment by whyscream** [comment]
The problem with using the KV filter is that you can't separate values from string `"2/3"` into integer `2` and  `3`. 

I'm seeing now that I have no test containing the `auth=` counter. I'll add that.
