### ISSUE TITLE
optional field not optional

### ISSUE THREAD

**Issue by lukbaum** [whyscream/postfix-grok-patterns#122]
The following line

`Nov 22 18:57:55 SERVER postfix/qmgr[1671]: QID: from=<>, size=3618, nrcpt=1 (queue active), QID: from=<>, size=3618, nrcpt=1 (queue active)`

is parsed such that the field

`postfix_from`

contains

`>`

=> postfix_from should be optional

**Comment by whyscream** [comment]
You input is correctly parsed into the `postfix_keyvalue_data` field. The `kv` plugin should process the data correctly using the `trim_value` parameter as set at https://github.com/whyscream/postfix-grok-patterns/blob/44d8da8e3772c53e12d472b04e17a678057257da/50-filter-postfix.conf#L174, but maybe you founda bug in the `kv` plugin in your version of logstash? 

In newer versions of logstash you could try to adapt the kv filter setting to use `include_brackets` or `remove_char_value`. I'm reluctant to add that to the repositoy when the current method is supported by all versions of logstash and the other options are only available in newer releases..

**Comment by lukbaum** [comment]
Ok. Unfortunately, I don't have the data anymore, I had it only for test purposes. I'll inverstigate further if it occurs again and close the ticket for now.

Nice work by the way :)
