### ISSUE TITLE
program field is null

### ISSUE THREAD

**Issue by agentfrostyqueen** [whyscream/postfix-grok-patterns#128]
I created mutate filter in conjunction with the two file
```
filter {
  mutate {
    rename => [
      "syslog_program", "program",
      "syslog_message", "message"
    ]
  }
}
```
I restarted logstash and ran bin/logstash -f 50-filter-postfix.conf
But all program field shows null value
![1](https://user-images.githubusercontent.com/40740392/42203114-60f0f3ea-7ed0-11e8-88cd-7f1c43793696.PNG)

**Comment by whyscream** [comment]
What does an original message look like in terms of fields and data? maybe you need a different mapping?

**Comment by whyscream** [comment]
Closing this, please reopen when you can respond to the questions posed.
