### ISSUE TITLE
Message-id produces wrong result

### ISSUE THREAD

**Issue by tomsommer** [whyscream/postfix-grok-patterns#130]
The following message-id breaks the parser:
`
Aug 14 15:29:57 X postfix/cleanup[11962]: 41qYP05TZCz5xY9: message-id==?utf-8?Q?=3CE1F7DC2C-82B5-4927-B0DB-0179227E665C=40aalborgf?=? =?utf-8?Q?=C3=B8rstehj=C3=A6lp=2Edk=3E?=
`

I suspect it is because of the space

**Comment by whyscream** [comment]
I saw the issue on the  postfix mailing list indeed. The problem here is that we use the default key-value functionality of logstash to extract the message id. I'll need to find out whether we can tune that to extract values containing `=` correctly.

**Comment by whyscream** [comment]
For future reference: http://postfix.1071664.n5.nabble.com/message-id-logging-broken-by-utf8-td97153.html

**Comment by tomsommer** [comment]
Seems to be fixed in latest patterns

**Comment by whyscream** [comment]
Hi Tom, 
Which version of elasticsearch have you verified this with? That would be useful information for other users having this (or similar) issues.

**Comment by tomsommer** [comment]
5.X
