### ISSUE TITLE
program / message vs. syslog_program / syslog_message

### ISSUE THREAD

**Issue by ulab** [whyscream/postfix-grok-patterns#131]
I'm new with logstash, so I based a lot of my setup on the documentation.

In the [configuration examples](https://www.elastic.co/guide/en/logstash/current/config-examples.html#_processing_syslog_messages) they are creating syslog_* fields instead of the one without the prefix you are using.

Changing the field names might help others that base their setup on the official example (and realizing that 50-filter-postfix.conf is run before logstash-syslog.conf ;-)).

**Comment by whyscream** [comment]
As can be read in the README of this project, the expected input is based on the defaults generated by the `syslog input plugin`, not on a random example. See https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html for details.
