### ISSUE TITLE
policyd-spf pattern

### ISSUE THREAD

**Issue by jowanw** [whyscream/postfix-grok-patterns#139]
Hello,

would it be possible to add patterns for policyd-spf?

Example:
`Apr 15 11:37:46 examplemx01 policyd-spf[28662]: None; identity=mailfrom; client-ip=192.192.192.192; helo=mail.example.com; envelope-from=name@example.com; receiver=target@anotherexample.org`

The result would be:
program: policyd-spf
postfix_client_hostname: mail.example.com
postfix_client_ip: 192.192.192.192
postfix_from: name@example.com
postfix_to: target@anotherexample.com
postfix_spf_status: none

Status can be Pass, Fail or None (none = no spf record)

**Comment by whyscream** [comment]
Hi, it would be nice to have logstash filtering for other tools ready-to-go like in this repo.

But I don't think it's a good idea to expand this project with all kinds of logging from email/spam/virus/policy related utilities. Feel free to start a separate project for bundling these kinds of logging. Please let me know, and I will add a link to the README to such repositories.
