### ISSUE TITLE
Polluted fields like #143

### ISSUE THREAD

**Issue by katerius** [whyscream/postfix-grok-patterns#149]
Like issue #143 I still get the same problem.

Hello, i got the same problem, utf8 chain was creating fields like `"postfix_?utf-8?B?N2NmMGJmYjEyMTViYkBjb250YWN0LWVyYW0uZnINCj4"` with value `"?="`
My data are the same as you, two chain with a space and no bracket and it seem to trigger a kv filter anyway.

My message :
`
2B8A6446CC29: message-id==?utf-8?B?PDIwMjAwNjEyXzE2NDkwN19jZWI2OTlhMWU5Mjk0YzE1ODAz?=? =?utf-8?B?N2NmMGJmYjEyMTViYkBjb250YWN0LWVyYW0uZnINCj4=?=`

The fix does not seems to work

**Comment by whyscream** [comment]
@katerius can you the complete resulting logstash entry (like shown in #143)?

**Comment by katerius** [comment]
Here is the document : 
`Discover
Visualize
Dashboard
Canvas
Maps
Machine Learning
Metrics
Logs
APM
Uptime
SIEM
Dev Tools
Stack Monitoring

    Management

{
  "_index": "postfix-2020.06-reindexed-r",
  "_type": "_doc",
  "_id": "NbCqrXIBIRasp4huNzzr",
  "_score": 1,
  "_source": {
    "severity_label": "Informational",
    "pid": "32445",
    "host": "10.0.3.21",
    "logsource": "mailrly01",
    "tags": [
      "_grok_postfix_success",
      "_postfix"
    ],
    "postfix_?utf-8?B?NzQxOGVkM2YyOGFjOEBuZXdzLWFpZ2xlLmNvbQ0KPg": "=?=",
    "timestamp8601": "2020-06-13T14:31:53.168733+02:00",
    "program": "postfix/cleanup",
    "message": "246884008A: message-id==?utf-8?B?PDIwMjAwNjEzXzE0MzE1Ml8xMDcyZjVhZDdlZjU0M2Q0OWQ0?=? =?utf-8?B?NzQxOGVkM2YyOGFjOEBuZXdzLWFpZ2xlLmNvbQ0KPg==?=",
    "facility": 2,
    "postfix_queueid": "246884008A",
    "priority": 22,
    "severity": 6,
    "@version": "1",
    "@timestamp": "2020-06-13T12:31:53.168Z",
    "postfix_message-id": "=?utf-8?B?PDIwMjAwNjEzXzE0MzE1Ml8xMDcyZjVhZDdlZjU0M2Q0OWQ0?=?",
    "timestamp": "2020-06-13T14:31:53.168733+02:00",
    "facility_label": "mail"
  },
  "fields": {
    "timestamp8601": [
      "2020-06-13T12:31:53.168Z"
    ],
    "@timestamp": [
      "2020-06-13T12:31:53.168Z"
    ],
    "timestamp": [
      "2020-06-13T12:31:53.168Z"
    ]
  }
}`

**Comment by whyscream** [comment]
@katerius I've ran your example as a test in test suite [1], but it passes the test nicely, because of the fix added for #143. My only explanation for your problem is that you forgot to update the grok file after the changes applied for #143.

[1] https://github.com/whyscream/postfix-grok-patterns/compare/149-test

**Comment by whyscream** [comment]
Closed, no response.
