### ISSUE TITLE
No smtpd NOQUEUE mails in log

### ISSUE THREAD

**Issue by azhinu** [whyscream/postfix-grok-patterns#150]
Hi there. With aggregation module I got no NOQUEUE messages. (like this: postfix/smtpd: NOQUEUE: reject: RCPT from test.sender: 450 4.2.0 <test@receptient>: Recipient address rejected: Greylisted for 60 seconds; from=<test@test.sender> to=<test@receptient> proto=ESMTP helo=<test.sender>
This cause by this string in aggregation module.
 `  if ![postfix_queueid] {
    drop {}`
So, there is a two solutions:
First -- remove these messages drop, but it will cause a large amount of useful logs.
Second -- add NOQUEUE as a kind of queue id. I more like a second way.

So, if you agree, I can make a pull request with 

POSTFIX_QUEUEID ([0-9A-F]{6,}|[0-9a-zA-Z]{12,}|NOQUEUE)
and
POSTFIX_SMTPD_NOQUEUE %{POSTFIX_QUEUEID:postfix_queueid}: blablabla

**Comment by c0mrade** [comment]
This is a great idea

**Comment by whyscream** [comment]
Thank you for waiting patiently, I merged this change (finally).

**Comment by ulab** [comment]
I don't use the aggregation feature, but doesn't this change result in Logstash trying to aggregate multiple NOQUEUE entries into one?

**Comment by whyscream** [comment]
That might be true, good call. I don't use it either, and nobody complained :)

For now I added a statement to ignore events with such a queue id during aggregation. I don't want to exclude the `NOQUEUE` from the `postfix_queueid` and change existing behavior for everyone.

**Comment by ulab** [comment]
See my comment on your change in #190. 

I do think this might remove the `NOQUEUE` lines again which this issue was about in the first place? ;-)

Instead I think it would be better to add a test to the conditionals that do the aggregation, but since you are not using it either, I am not sure how to test it 😉
