### ISSUE TITLE
Pattern for smtp / PIX workarounds missing?

### ISSUE THREAD

**Issue by ulab** [whyscream/postfix-grok-patterns#157]
I am not using the patterns directly in logstash, but tried to re-create them for direct ingest streams. So I am not sure if I might have missed a pattern, but I just stumbled over this where the GROKs did not match:

Jul 29 08:48:33 mx-out-01 postfix/smtp[9833]: B0ADE20FC7: enabling PIX workarounds: disable_esmtp delay_dotcrlf for example.com[93.184.216.34]:25

**Comment by whyscream** [comment]
The patterns are meant to extract useful data points from the log stream. If no one is interested in the fact that the PIX workarounds are triggered for certain hosts, there won't be a pattern for that. No one ever put in a request, until now :)

**Comment by ulab** [comment]
I just thought it might be useful to find when you filter for the Queue-ID, IP or client. :)
