### ISSUE TITLE
Fields are not loaded if an aggregate filter is used

### ISSUE THREAD

**Issue by Devastate-D** [whyscream/postfix-grok-patterns#159]
Thank you very much for the work done. Everything works fine. 
I'm using the following setup: Filebeat -> Logstash -> Elasticsearch
I use your filters in my work. I noticed one peculiarity, if I use 51-filter-postfix-aggregate.conf, data on the postfix/anvil and postfix/scache fields cease to flow to elasticsearch. As soon as I remove the aggregation, these fields are loaded into elastic. Also, the fields that I set manually stop loading.
Tell me please, what can be changed in 51-filter-postfix-aggregate.conf for more correct work?
Thanks for help

**Comment by Devastate-D** [comment]
Removed part of the code with the postfix_queueid drop.
 ```
if ![postfix_queueid] {
    drop {}
  } else
```
I do not know how long this is the correct solution, but the fields began to be loaded into elastic.

**Comment by whyscream** [comment]
Hi,

the aggregated config is contributed, I never used it. Lines without `queueid` can't be aggregated, so it sounds plausible to remove them if your goal is aggregation. Also, the `anvil` and `scache` logging is never applicable to a single message, as far as I know. Is it useful to keep this information around?

**Comment by Devastate-D** [comment]
I agree that the `anvil` and `scache` fields are not very informative, nevertheless the aggregation works and the new fields that I want to add to myself are not dropped.
Еhank you for this template and filter.
