### ISSUE TITLE
Messages status doesn't work

### ISSUE THREAD

**Issue by odiks** [whyscream/postfix-grok-patterns#160]
First, **thank you** for this dashboard.

So, I have been configured all tools like in the description, but the panel "Messages Total", "Messages status totals" and "status Over time" doesn't work, I have only the logs at the bottom . 

Have you an idea to resolv this problem ? 

Thank you 
![github-issue-postfix-kibana](https://user-images.githubusercontent.com/47142092/148204411-7f299319-a5b6-4b0f-8b69-7a89cdd419c2.PNG)

**Comment by whyscream** [comment]
I'm sorry, I don't support kibana, just the grok patterns.
