### ISSUE TITLE
Grok pattern POSTFIX_STATUS_CODE_ENHANCED can't parse "5.1.10"

### ISSUE THREAD

**Issue by leweafan** [whyscream/postfix-grok-patterns#161]
Grok pattern POSTFIX_STATUS_CODE_ENHANCED \d\.\d\.\d  can not parse "5.1.10" cause 10 is two digit number.
Please use pattern "\d+\.\d+\.\d+"

**Comment by whyscream** [comment]
Hi @leweafan. Thanks for reporting, I'll look into it shortly.

**Comment by whyscream** [comment]
Based on https://en.wikipedia.org/wiki/List_of_SMTP_server_return_codes#Enhanced_status_code I'll update the pattern to `\d.\d+.\d+`

**Comment by whyscream** [comment]
Resolved in #162

**Comment by leweafan** [comment]
@whyscream thanks for the quick reply!
