### ISSUE TITLE
ECS authentication fields for SIEM

### ISSUE THREAD

**Issue by leweafan** [whyscream/postfix-grok-patterns#170]
Postfix has authentication messages for failed attempt. But ECS fields important for SIEM like event.category, event.type, event.action, event.outcome are missing.

```
if “postfix.message” =~ /SASL LOGIN authentication failed: authentication failure/  {
    mutate {
        add_field => {
            "event.category" = "authentication"
            "event.kind" => "event"
            "event.type" => "start"
            "event.outcome" => “failure”
    }
}
```

**Comment by whyscream** [comment]
Same as #169: not everybody uses ECS or SIEM (I have no idea what that is). Apply this to your local setup.
