### ISSUE TITLE
RCPT_TO / Return-Path

### ISSUE THREAD

**Issue by dmgeurts** [whyscream/postfix-grok-patterns#171]
Comparing details from Logstash and Exchange Online I noticed that EOP reports the Return-Path as the `from` field (possibly wrongly? But that's another issue) and so I wondered why I'm only recording the `To` and `From` addresses. Checking the code I see no reference to `rcpt_to` or `return-path`, has anyone added this to their filter?

It's relevant to me for tracking bounce message processing. Bounce notifications are supposed to go to the `Return-Path` address rather than the `from` address. I'm aware this isn't always adhered to by mailservers.

**Comment by whyscream** [comment]
Hi @dmgeurts 

Your question is not really clear on this, but I'm assuming for the sake of clarity that:
- This is about a Postfix server (sending end) sending to Exchange (receiving end)
- You are on the sending end

`Return-Path` is a header that is added by the receiving server. Normally it is generated by using the `RFC5321.MailFrom` (e.g. the address that was sent during SMTP transfer in the `MAIL FROM` command). This header is therefor not available to the sending server. Apart from that, Postfix never cares about headers anyway, by default it only logs SMTP envelope data.

The Postfix server on the sending end will log the original sender in the `qmgr` logline when it starts processing the queued message, f.i. in https://github.com/whyscream/postfix-grok-patterns/blob/master/test/qmgr_0002.yaml, but not the actual `MAIL FROM` contents that the `smtp` program will send, AFAIK. Under normal circumstances this should be equal to the value in the `qmgr` logline, though. 

NB I'm unsure how logs look like if you're rewriting the sender with Postfix config on the sending server. Feel free to contribute examples if you have them.

**Comment by whyscream** [comment]
The reason that you're not seeing this in the logstash filter code is because the `from` is parsed using generic key-value parsing.

**Comment by whyscream** [comment]
```
Nov 15 11:40:22 mailserver postfix/qmgr[15810]: B750520112: from=<local-user@example.net>, size=2080, nrcpt=1 (queue active)
Nov 15 11:40:25 mailserver postfix/smtp[21481]: Untrusted TLS connection established to cust21691-2.in.mailcontrol.com[85.115.58.190]:25: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Nov 15 11:40:26 mailserver postfix/smtp[21481]: B750520112: to=<recipient@remote.example.org>, relay=cust21691-2.in.mailcontrol.com[85.115.58.190]:25, delay=3.3, delays=0.13/0.01/2.2/0.95, dsn=2.0.0, status=sent (250 2.0.0 2AFAeNTj000812 Message accepted for delivery)
Nov 15 11:40:26 mailserver postfix/qmgr[15810]: B750520112: removed
```
In this SMTP conversation the remote server `cust21691-2.in.mailcontrol.com` is probably going to use `local-user@example.net` as the return path.

**Comment by dmgeurts** [comment]
@whyscream, my apologies!

Yes, your assumption is correct. I'm tracking emails forwarded from Postfix to O365. Postfix appears to be logging the `rcpt-to` address and O365 logs the `from` address.

```
Nov 18 19:05:17 host postfix/cleanup[3304557]: A82C61E1A28: message-id=<ce9d7fd91f5516a37bbe32f9197aa36b@other-host.domain.com>
Nov 18 19:05:17 esh01 postfix/qmgr[2855631]: A82C61E1A28: from=<service+bounce@domain.com>, size=13780, nrcpt=6 (queue active)
Nov 18 19:05:18 host postfix/smtp[3304739]: A82C61E1A28: to=<someone@domain.com>, relay=domain-com.mail.eo.outlook.com[104.47.17.74]:25, delay=1.3, delays=0/0.01/0.15/1.1, dsn=2.6.0, status=sent (250 2.6.0 <ce9d7fd91f5516a37bbe32f9197aa36b@other-host.domain.com> [InternalId=15298673512055, Hostname=AS4P190MB2021.EURP190.PROD.OUTLOOK.COM] 22586 bytes in 0.148, 148.174 KB/sec Queued mail for delivery)
Nov 18 19:05:18 host postfix/qmgr[2855631]: A82C61E1A28: removed
```

But O365 records:
![image](https://user-images.githubusercontent.com/2071992/202821524-324a3c76-a6be-483b-8019-d0a1558a7a1b.png)

I know that the service is configured with `From: service+no-reply@` and `Return-Path:service+bounce@`.

I'm not complaining, but just noticed the difference and am wondering if there's anything that I could do to log both. But I guess that would have to start with Postfix actually logging both header fields.

**Comment by whyscream** [comment]
I am still unsure what your issue is. Postfix is sending with `service+bounce@domain.com` in the RFC5321.MailFrom, so O365 will use that when bounces occur. 

I have zero knowledge on O365 (and I would prefer to keep it that way 😉), but the fact that O365 shows the `service+no-reply@...` address as the "Sender" might just be because O365 shows you the E-mail header value and not the RFC5321.MailFrom. Thus, the log/interface you are looking at is not suitable for researching bounces.

The E-mail headers are just content, they can contain anything. If you're tracking bounces, the only thing you should be interested in is RFC5321 addresses (i.e. the SMTP envelope data).

That being said, you can configure Postfix to log E-mail header data using [header checks](https://www.postfix.org/postconf.5.html#header_checks). Note again that Postfix cannot reliably log the Return-path header as it is non-existent, or may be discarded and replaced when 0365 accepts the message. But the value that Postfix offers O365 as input for the Return-path data, is already logged by the `qmgr`.

**Comment by whyscream** [comment]
Closing this issue, feel free to reopen.
Note that I haven't seen any question yet directly related to this project, as the subject was mostly the content of  log data, and not parsing it.
