### ISSUE TITLE
postfix_from and postfix_to address

### ISSUE THREAD

**Issue by jcz1** [whyscream/postfix-grok-patterns#173]
Hello.

Some changes for postfix_from, postfix_to adress or mail_size, delays etc:

POSTFIX_QMGR_ACTIVE %{POSTFIX_QUEUEID:postfix_queueid}: from=<%{EMAILADDRESS:postfix_from}>, size=%{NUMBER:postfix_mail_size}, nrcpt=%{NUMBER:postfix_recipient_numbers} \(%{GREEDYDATA:postfix_status}\)

POSTFIX_SMTP_DELIVERY %{POSTFIX_QUEUEID:postfix_queueid}: to=<%{EMAILADDRESS:postfix_to}>, relay=%{GREEDYDATA:postfix_smtp_relay}, delay=%{GREEDYDATA:postfix_smtp_delay}, delays=%{GREEDYDATA:postfix_smtp_delays}, dsn=%{GREEDYDATA:postfix_smtp_dsn}, status=%{STATUS_WORD:postfix_status}( \(%{GREEDYDATA:postfix_smtp_response}\))?

**Comment by whyscream** [comment]
Hello @jcz1, I think these variables are already supported by the key-value parsing that applied to the whole line. Could you please provide an example log line that is currently not parsed correctly, and the values that are not extracted from it?

**Comment by whyscream** [comment]
Hi,

Did you actually read the [README](https://github.com/whyscream/postfix-grok-patterns/blob/master/README.md) and configure logstash as intended? Or had any problems doing that, which you failed to mention? There is a reason the patterns work the way they do right now.
