### ISSUE TITLE
filter postfix aggreate does not aggreate 100% log

### ISSUE THREAD

**Issue by thangnguyennang** [whyscream/postfix-grok-patterns#175]
I do a test: use tool "smtp-source" (Postfix tool) send 100 emails to test filter aggreate, the result:
- first test: filter aggreate success, I see a report 100 emails in Kibana
- second test: filter aggreate not expected, I see a report 98 emails in Kibana, lost 2 emails
- third test: filter aggreate success, I see a report 100 emails in Kibana
- forth test: filter aggreate not expected, I see a report 97 emails in Kibana, lost 3 emails

may be bug in your filter postfix aggreate's code.

Thanks for your help.

My test environment:
- logstash 7.17.9-1
- elasticsearch 7.17.9-1
- kibana 7.17.9-1
- filebeat 7.17.8
- postfix 2.10.1

**Comment by thangnguyennang** [comment]
Hi,
If I set **pipeline.workers: 1** in file pipeline.yml of logstash (default is 2), filter aggreate success in all test.

**Comment by whyscream** [comment]
The pipeline configuration was contributed in https://github.com/whyscream/postfix-grok-patterns/pull/147, I have no firsthand experience using it. Just to rule out any other issues:
- Are all 100 sent messages actually in postfix?
- Can you find anything remarkable in the postfix logging for the messages that you're missing in logstash (if you compare postfix queue ids, you should be able to find the missing data in logstash)?
