### ISSUE TITLE
Filebeat module

### ISSUE THREAD

**Issue by leweafan** [whyscream/postfix-grok-patterns#176]
Hello @whyscream!

I've created [filebeat postfix module](https://github.com/leweafan/filebeat-postfix) using grok patterns from this repo and would like to make PR for elastic beats repo.

I can't make it without your agreement.

**Comment by whyscream** [comment]
Hi @leweafan 

Nice to see that you were able to create something new from the code I published here over the years. As the [code is published under the 3-clause BSD license](https://github.com/whyscream/postfix-grok-patterns#license), you don't need my permission or agreement to use the code.

I've just added a LICENSE file to the project for more clarity, you can include that file with your code.

Good luck with your project!
