### ISSUE TITLE
How to use this script ?

### ISSUE THREAD

**Issue by goof03** [whyscream/postfix-grok-patterns#41]
Hi ! 
I'm starting to use logstach and find your work for postfix but how i can use this with my others configurations.

I try this (after adding your 2 files) : 
```
input{
  file {
    type => "linux-syslog"
    path => "/var/log/syslog"
  }
}
```
But without success … linux-syslog index it with syslog_program not program like in your filter.

thanks for help

**Comment by whyscream** [comment]
You could add a mutate filter before the postfix one, using rename http://www.logstash.net/docs/1.4.2/filters/mutate#rename

File /etc/logstash/conf.d/40-filter-mutate-pre-postfix.conf:
```
filter {
  mutate {
    rename => [
      "syslog_program", "program",
      "syslog_message", "message"
    ]
  }
}
```

Use this to manipulate the message format until you have the required fields available. Only `message` and `program` are needed I think.

**Comment by goof03** [comment]
Ok seems to work now thanks.

I get another problem : I'll try to make a «top 10 senders» in kibana but when i try a table terms on postfix_from the terms (emails address) are split by the @ char. 

Do you have an idea why ? please

**Comment by whyscream** [comment]
Sounds like a kibana issue, in logstash the addresses are not split. You could try: http://www.elasticsearch.org/community/

**Comment by agentfrostyqueen** [comment]
Im also using file input but I have a different result.
I created _/etc/logstash/conf.d/40-filter-mutate-pre-postfix.conf_ as mentioned above.

--------------Modified Content of 50-filter-postfix.conf ----------------------------------
`input {
   file {
     path => "/var/log/maillog-20180611"
   }
}

<content of 50-filter-postfix.conf>

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => ["log-%{+YYYY.MM.dd}"]
  }`

![gith](https://user-images.githubusercontent.com/40740392/42136641-001db6f0-7d92-11e8-8eb7-1dfc1cac2c6f.PNG)

**Comment by whyscream** [comment]
@agentfrostyqueen I think you're missing the `type => "linux-syslog"` from the top comment. The log lines aren't split into date, `program` and `message` parts, everything is in the `message` now which is not good.

**Comment by agentfrostyqueen** [comment]
@whyscream I added the type but still same result
