### ISSUE TITLE
postfix/local parsing

### ISSUE THREAD

**Issue by martin21** [whyscream/postfix-grok-patterns#42]
Hi! I found you do not parse postfix/local lines. On purpose? I started at postfix/local parsing. Just quick today, I can make a pull request next week:

postfix-grok:

    # local patterns
    # Fluent format: /^(?<queueid>[^ ]*): to=<(?<rcpt-to>[^ ]*)>, [^*]* relay=(?<relay>[^ ]*), [^*]* status=(?<status>[^ ]*)/
    POSTFIX_LOCAL_TO to=%{NOTSPACE:postfix_to}
    POSTFIX_LOCAL_RELAY relay=%{POSTFIX_RELAY_INFO}
    POSTFIX_LOCAL_DELAY delay=%{NUMBER:postfix_delay_total}
    POSTFIX_LOCAL_DELAYS delays=%{POSTFIX_DELAYS}
    POSTFIX_LOCAL_STATUS status=%{NOTSPACE:postfix_status}
    POSTFIX_LOCAL %{POSTFIX_QUEUEID:postfix_queueid}: %{POSTFIX_LOCAL_TO}, [^*]* %{POSTFIX_LOCAL_RELAY}, %{POSTFIX_LOCAL_DELAY}, delays=%{POSTFIX_DELAYS}, [^*]* %{POSTFIX_LOCAL_STATUS

logstash config:

    } else if [syslog_program] =~ /^postfix.*\/local$/ {
        grok {
            patterns_dir   => "/etc/logstash/patterns.d"
            match          => [ "message", "%{POSTFIX_LOCAL}" ]
            tag_on_failure => [ "_grok_postfix_local_nomatch" ]
            add_tag        => [ "_grok_postfix_success" ]
        }

It works for:

Feb 18 16:38:07 linloglogstash postfix/local[5789]: 2A22C263F6: to=<teamix@linloglogstash.some.domain>, orig_to=<root@localhost>, relay=local, delay=0.07, delays=0.04/0/0/0.03, dsn=2.0.0, status=sent (delivered to command: procmail -a "$EXTENSION")

but not for:

Feb 18 16:26:39 linloglogstash postfix/local[5663]: 892A0205B6: to=<ghdsgfhdslfh@localhost>, relay=local, delay=0.05, delays=0.02/0/0/0.02, d
sn=5.1.1, status=bounced (unknown user: "ghdsgfhdslfh")

due to no orig_to in there that I skip in POSTFIX_LOCAL. Best would be to allow for optional "something=" parameters in between, but do not expect them either.

**Comment by whyscream** [comment]
Hi Martin, thanks for your interest. 

I don't have any patterns for local delivery because I don't use that. So no sample log lines, and no personal need. I'll add the examples you provided. Supporting them is easy since they are already covered by the default key-value parsing.

**Comment by whyscream** [comment]
The changes in #43 should work for logstash users, since the logstash config uses key-value processing after the grok work. I don't know if this solution works for fluentd (which you seem to use).

**Comment by martin21** [comment]
Thank you, Tom.

Hmmm, does this also work with the delays=0.04/0/0/0.03 key value? Cause there it has several values in one key, my attempt at parsing them splitted them up like you did for the qmgr lines.

My filters parsed it as:

"postfix_delay_total":"1.1","postfix_delay_before_qmgr":0.98,"postfix_delay_in_qmgr":0.06,"postfix_delay_conn_setup":0,"postfix_delay_transmission":0.03,"postfix_status":"sent"

(okay, I don´t know whether the labels for the attributes are correct, I just reused your qmgr stuff, but I can look this up)

I am trying your pattern nevertheless as it would not fail on my second example line.

**Comment by martin21** [comment]
Okay, now I get it. This parsing seems to be stacked. qmgr uses the same way. And well, it works and separates the delays nicely.

BTW I am preparing slides for a logfile analysis training, so I am looking at both fluentd and logstash. I don´t know yet, whether fluent-plugin-grok-parser can take these postfix patterns yet, but I may try.

**Comment by whyscream** [comment]
I guess the patterns should be fine as grok is a generic library. But the stacked approach and the k/v parsing is built as logstash functionality, and I have no idea if you can replicate that using fluentd.

Good luck with your training! :)

Regards,
	Tom
