### ISSUE TITLE
elastic search mapping

### ISSUE THREAD

**Issue by hacktvist** [whyscream/postfix-grok-patterns#66]
Hello,

can anybody list what is the mapping they used for elastic search.

Any help will be appreciated.

**Comment by whyscream** [comment]
I don't use any special mapping in ES for postfix logs. But my dataset is not that large that it would make a difference.

**Comment by hacktvist** [comment]
can you share which mapping you use which, will retrieve fields like (bounce, dsn, status,queue...)
