### ISSUE TITLE
Explaining some keyword

### ISSUE THREAD

**Issue by bachkhoabk47** [whyscream/postfix-grok-patterns#67]
Dear authors, 
My name is Tan and I come from Vietnam.
You know, at this time, I'm focusing on processing log for monitoring, ...
I read a lot of documents and then I see your art was so useful.
But having some keywords that I could not understand well, so that why can why explain it to me.
For example:  

if [program] =~ /^postfix.*\/anvil$/ {
        grok {
            patterns_dir   => "/etc/logstash/patterns.d"
            match          => [ "message", "%{POSTFIX_ANVIL}" ]
            tag_on_failure => [ "_grok_postfix_anvil_nomatch" ]
            add_tag        => [ "_grok_postfix_success" ]

---> in if[program]:    what's program and its function?

Thank you and best regards!

**Comment by bachkhoabk47** [comment]
Hi, I read the log again and maybe I've understand about that.
For example log:  Sep 30 00:00:02 npcSendingGW1 postfix/master[1480]
--> prgram: postfix/master[1480].
That's right for me! :)
Thanks!

**Comment by whyscream** [comment]
Yes, that's correct :)
