### ISSUE TITLE
The way to match

### ISSUE THREAD

**Issue by bachkhoabk47** [whyscream/postfix-grok-patterns#68]
Dear authors.
Like issue #66:
I have some confusions that I saw in 50-filter-postfix.conf and postfix.grok
First, I push my log up. For example, like this:
Sep 30 00:00:02 SendingGW2 postfix/pickup[14400]: 321511FE45: uid=0 from=<root>

and then the log will be mapped in [program] =~ /^postfix.*\/pickup$/ field.
--> after that it will go to /etc/logstash/patterns.d directory for processing.
and the log will find POSTFIX_PICKUP in /etc/logstash/patterns.d for matching.
POSTFIX_PICKUP %{POSTFIX_KEYVALUE}
--> POSTFIX_KEYVALUE %{POSTFIX_QUEUEID:postfix_queueid}: %{GREEDYDATA:postfix_keyvalue_data}

With my log matching, I just see: postfix_queueid=321511FE45
but be confused about "uid=0 from=<root>" matching to %{GREEDYDATA:postfix_keyvalue_data}

Should I need to change your configuration or not? and how can I edit your file to matching my log.
Thanks and best regards.

**Comment by whyscream** [comment]
The data in `postfix_keyvalue_data` is processed again at https://github.com/whyscream/postfix-grok-patterns/blob/master/50-filter-postfix.conf#L157

That should result in `postfix_uid` and `postfix_from` fields

**Comment by bachkhoabk47** [comment]
Yeah! Thanks for your feedback immediately
After I output, I can see postfix_uid and postfix_from, but could not see the state of the tag_on_failure or add_tag.
So I think I got some wrongs and mistakes. 
So do you think that we should see the result of the tag_on_failure or add_tag give back?
Thanks

**Comment by whyscream** [comment]
The tag is visible in the `tags` field. However, the tags are mostly for debugging: I have a kibana dashboard configured that shows me  all events that don´t have `postfix_success` tagged, so I can add new patterns based on those.

**Comment by bachkhoabk47** [comment]
Thanks for your feed back me!
In fact that I'm confusing.
In my opinion, if the log can match to the logstash-grok, it should be returned a result like tags field that we configured before but could not see. 
Ok, lets me trying to research more.
Thank you so much! :)

**Comment by bachkhoabk47** [comment]
program? in  "if [program] = ....."
See here to understand https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/syslog-ng-patterndb-operation.html
Thanks author!

**Comment by whyscream** [comment]
The input format is (as mentioned in the README) on the syslog input filter for logstash (see https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html, https://github.com/logstash-plugins/logstash-input-syslog).

While the documentation does not provide sample event data, it all comes down to the `%SYSLOGLINE` grok pattern provided by logstash, see: https://github.com/logstash-plugins/logstash-input-syslog/blob/master/lib/logstash/inputs/syslog.rb#L77 which provides the `program` field.

I have no idea if the syslog input filter works with syslog-ng log format, I use rsyslog for this purpose. If it doesn't, please file a bug with them.
