### ISSUE TITLE
A little error

### ISSUE THREAD

**Issue by moebiuseye** [whyscream/postfix-grok-patterns#70]
Hi,

I've installed the grok patterns and the filter conf file. 

I just had to add this to the top of the grok file to make it work: 

    HOST [0-9a-zA-Z\.]*

Otherwise, I had this error: 

    :message=>"The error reported is: \n  pattern %{HOST:postfix_client_hostname} not defined"}

I thought maybe you would know if my change is good and if you need to add this to the file yourself or in the documentation somewhere. 

I'm running the 2.0.0 version on Centos 7, and after I added the line, it seems to be working fine.

**Comment by whyscream** [comment]
This is one of the logstash builtin patterns, AFAIK. Which version of logstash are you running?

**Comment by moebiuseye** [comment]
The 2.0.0

**Comment by whyscream** [comment]
Thanks for reporting. Fix is in #71, should work with both v2.0.0 and older versions.
