### ISSUE TITLE
Field name [postfix_http://www.spamhaus.org/query/bl?ip] cannot contain '.'"

### ISSUE THREAD

**Issue by tomsommer** [whyscream/postfix-grok-patterns#73]
I'm getting

```
"error"=>{"type"=>"mapper_parsing_exception", "reason"=>"Field name [postfix_http://www.spamhaus.org/query/bl?ip] cannot contain '.'"}}}, :level=>:warn}
````

when shipping to ES 2.0

using latest grok patterns

**Comment by whyscream** [comment]
Can you share the full log line? Otherwise it's hard to debug...

**Comment by tomsommer** [comment]
I'm not seeing this anymore. Closing. Will re-open if it occurs again.

**Comment by whyscream** [comment]
I'm still interested in a full example log line that triggered this behaviour in the past, so I can add a test case for it.
