### ISSUE TITLE
 add include_keys into kv

### ISSUE THREAD

**Issue by daewo** [whyscream/postfix-grok-patterns#75]
Hi,

please add include_keys => [ "proto", "from", "helo", "client", "message-id", "to", "relay", "delay", "delays", "dsn" ] into kv {}.
sometimes kv create field like postfix_10934gjoiasjgoeirqjg90234j09gqe it is because sometimes postfix from contains "=" for example (10934gjoiasjgoeirqjg90234j09gqe=domain.com@namcore.co.uk)

david

**Comment by whyscream** [comment]
Do you have a complete logline as an example?

**Comment by whyscream** [comment]
This looks like the same issue as in #73, but I don't have any actual log samples that show this behaviour.

**Comment by daewo** [comment]
log line:
NOQUEUE: discard: MAIL from ccm231.constantcontact.com[208.75.123.231]: <bsdbdsfbw==_4343_sdfbddw==@in.constantcontact.com>: Sender address SPAM; from=<bsdbdsfbw==_4343_sdfbddw==@in.constantcontact.com> proto=ESMTP helo=<ccm231.constantcontact.com>

logstash field:
postfix_<bsdbdsfbw: =_4343_sdfbddw==@in.constantcontact.com:

----
log line:
NOQUEUE: discard: MAIL from smtp-coi-g03-007.aweber.com[204.194.223.7]: <wbwoikbmwio=@smtp-coi-g03-007.aweber.com>: Sender address emailmarketing; from=<wbwoikbmwio=@smtp-coi-g03-007.aweber.com> proto=ESMTP helo=<smtp-coi-g03-007.aweber.com>

logstash field:
postfix_<wbwoikbmwio: @smtp-coi-g03-007.aweber.com:

----
log line:
NOQUEUE: discard: MAIL from mx193.kiwwimail.co.uk[109.230.203.193]: <members-dkopwnrrrnae=domain.com@namcore.co.uk>: Sender address SPAM; from=<members-dkopwnrrrnae=domain.com@namcore.co.uk> proto=ESMTP helo=<mx193.kiwwimail.co.uk>

logstash field:
postfix_<members-dkopwnrrrnae:domain.com@namcore.co.uk:

----
log line:
NOQUEUE: discard: MAIL from mx157.kiwwimail.co.uk[109.230.203.157]: <members-gqeioj09333jss=domain.com@namcore.co.uk>: Sender address SPAM; from=<members-gqeioj09333jss=domain.com@namcore.co.uk> proto=ESMTP helo=<mx157.kiwwimail.co.uk>

logstash field:
postfix_<members-gqeioj09333jss:domain.com@namcore.co.uk:

**Comment by whyscream** [comment]
I cannot reproduce this.
The sample lines you are showing are not supported at all, due to the fact that discard was not supported for smtpd logging. I've added support that, but parsing keyvalue data is working without the bugs you're showing.

**Comment by whyscream** [comment]
```json
{
  "_index": "logstash-2015.11.29",
  "_type": "logs",
  "_id": "AVFTzZIN5hQpC6OZ9i-T",
  "_score": null,
  "_source": {
    "message": "E5C623D: from=<aap=noot@example.org>, size=460, nrcpt=1 (queue active)",
    "@version": "1",
    "@timestamp": "2015-11-29T15:12:39.000Z",
    "host": "2001:968:669:0:244:0:0:0",
    "priority": 22,
    "timestamp": "Nov 29 16:12:39",
    "logsource": "valerie",
    "program": "postfix-in/qmgr",
    "pid": "30263",
    "severity": 6,
    "facility": 2,
    "facility_label": "mail",
    "severity_label": "Informational",
    "postfix_queueid": "E5C623D",
    "tags": [
      "_grok_postfix_success"
    ],
    "postfix_from": "aap=noot@example.org",
    "postfix_size": 460,
    "postfix_nrcpt": 1
  },
  "sort": [
    1448809959000,
    1448809959000
  ]
}
```
As you can see, the `from=` is correctly expanded. Which version of logstash are you running?
My tests are done with logstash 1.4.5 (on ubuntu)

**Comment by daewo** [comment]
I have version 2.1 (centos).
Thank you for support.
Ok we can close this issue.
