### ISSUE TITLE
Is this compatible with the latest Logstash?

### ISSUE THREAD

**Issue by Yzord** [whyscream/postfix-grok-patterns#77]
Is this version compatible with latest Logstash and Kibana 4? The reason why i ask this is when i follow the readme i get this line in my logstash log and logstash service stops:

{:timestamp=>"2015-12-16T15:26:30.889000+0100", :message=>"Error: Expected one of #, input, filter, output at line 33, column 1 (byte 738) after "}
{:timestamp=>"2015-12-16T15:26:30.897000+0100", :message=>"You may be interested in the '--configtest' flag which you can\nuse to validate logstash's configuration before you choose\nto restart a running system."}

If i remove the 50-filter-postfix.conf file and restart logstash all is running again.

**Comment by whyscream** [comment]
Patterns are tested with logstash 2 grok patterns, but i haven't tested the complete logstash config with 2. However, [the problematic line] (https://github.com/whyscream/postfix-grok-patterns/blob/master/50-filter-postfix.conf#L33) (according to your error message), has nothing different from other lines in the file (f.i. l26 or 19).

Could you verify that you copy/pasted the file correctly?

As far as kibana: should not matter, this config does not interact with it at all (it just produces data that can be used with it).

**Comment by whyscream** [comment]
For good measure, I just installed logstash 2.1 on ubuntu trusty LTS using the elastic repo. adding the 50-filter-postfix.conf foile to the config directery and then running a configtest does not report any errors here:
```
$ /opt/logstash/bin/logstash --config /etc/logstash/conf.d/50-filter-postfix.conf --configtest
Configuration OK
```

I think you made a copy/paste error

**Comment by Yzord** [comment]
I did a wget of the file in the dir. But i will try the test thingie :-)
