### ISSUE TITLE
postfix/error program

### ISSUE THREAD

**Issue by username1366** [whyscream/postfix-grok-patterns#87]
These paterns doesn't work for postfix/error program

`tags:	  	_grokparsefailure, _grok_postfix_program_nomatch`

`message: 2DC5552A34: to=<testtest@yahoo.com>, relay=none, delay=63495, delays=63350/144/0/0, dsn=4.4.2, status=deferred (delivery temporarily suspended: lost connection with mta7.am0.yahoodns.net[98.136.216.22] while sending RCPT TO)`

**Comment by whyscream** [comment]
Hi, thanks for reporting
Can you supply the complete log message, including syslog date and process name etc?
And do you have more examples from the `postfix/error` process?

**Comment by username1366** [comment]
It's working after your last commit. Thank you!
